--BD2 - 2o Bim -Atividade de SQL - DDL - Tabelas do Projeto Pedido
DROP TABLE CLIENTE CASCADE CONSTRAINTS;

CREATE TABLE CLIENTE (
CODIGO_CLIENTE  NUMBER,
NOME            VARCHAR2(60) NOT NULL,
RUA             VARCHAR2(80) NOT NULL,
NR              NUMBER(4) NOT NULL,
BAIRRO          VARCHAR2(50) NOT NULL,
COMPLEMENTO     VARCHAR2(100) NULL,
CIDADE          VARCHAR2(50) NOT NULL,
UF              VARCHAR2(2) NOT NULL,
CEP             VARCHAR2(10) NOT NULL,
CONSTRAINT PK_CLIENTE PRIMARY KEY (CODIGO_CLIENTE)
);

DROP TABLE PF;

CREATE TABLE PF (
CODIGO_CLIENTE_PF   NUMBER,       
CNPF                VARCHAR2(14) NOT NULL,
RG                  VARCHAR2(10) NOT NULL,
DATA_NASCIMENTO     DATE         NOT NULL,
CONSTRAINT PK_PF PRIMARY KEY(CODIGO_CLIENTE_PF)
);

DROP TABLE PJ CASCADE CONSTRAINTS;

CREATE TABLE PJ (
CODIGO_CLIENTE_PJ   NUMBER,       
CNPJ                VARCHAR2(19) NOT NULL,
IE                  VARCHAR2(10) NOT NULL,
NOME_FANTASIA       VARCHAR2(60) NOT NULL,
CONSTRAINT PK_PJ PRIMARY KEY(CODIGO_CLIENTE_PJ)
);

DROP TABLE PRODUTO CASCADE CONSTRAINTS;

CREATE TABLE PRODUTO (
CODIGO          NUMBER NOT NULL,
DESCRICAO       varchar2(80) NOT NULL,
UNID_MEDIDA     varchar2(10) NOT NULL,
CONSTRAINT PK_PRODUTO PRIMARY KEY(CODIGO)
);

DROP TABLE VENDEDOR CASCADE CONSTRAINTS;

CREATE TABLE VENDEDOR (
MATRICULA       NUMBER NOT NULL,
NOME            varchar2(60) NOT NULL,
CNPF            varchar2(14) NOT NULL,
CONSTRAINT PK_VENDEDOR PRIMARY KEY(MATRICULA)
);

DROP TABLE FONE_CLIENTE CASCADE CONSTRAINTS;

CREATE TABLE FONE_CLIENTE (
NUMERO              varchar2(14) NOT NULL,
CODIGO_CLIENTE_FONE      NUMBER NOT NULL,
CONSTRAINT PK_FONE_CLIENTE PRIMARY KEY(NUMERO,CODIGO_CLIENTE_FONE)
);

ALTER TABLE FONE_CLIENTE
ADD CONSTRAINT FK_FONE_CLIENTE FOREIGN KEY(CODIGO_CLIENTE_FONE) REFERENCES CLIENTE(CODIGO_CLIENTE);

DROP TABLE FONE_VENDEDOR CASCADE CONSTRAINTS;

CREATE TABLE FONE_VENDEDOR (
NUMERO              varchar2(14) NOT NULL,
MATRICULA_VENDEDOR  NUMBER NOT NULL,
CONSTRAINT PK_FONE_VENDEDOR PRIMARY KEY(NUMERO,MATRICULA_VENDEDOR)
);

ALTER TABLE FONE_VENDEDOR
ADD CONSTRAINT FK_FONE_VENDEDOR FOREIGN KEY(MATRICULA_VENDEDOR) REFERENCES VENDEDOR(MATRICULA);

DROP TABLE PRATELEIRA CASCADE CONSTRAINTS;

CREATE TABLE PRATELEIRA (
CODIGO          NUMBER(3)       NOT NULL,
DESCRICAO       varchar2(50)    NOT NULL,
NUMERO_SECOES   NUMBER(2)       NOT NULL,
CONSTRAINT PK_PRATELEIRA PRIMARY KEY(CODIGO)
);

DROP TABLE PEDIDO CASCADE CONSTRAINTS;

CREATE TABLE PEDIDO (
NUMERO          NUMBER(6)       NOT NULL,
DATA            DATE            NOT NULL,
PRAZO_ENTREGA   DATE            null,
RUA             varchar2(80)    null,
NR              NUMBER(4)       null,
BAIRRO          varchar2(50)    null,
COMPLEMENTO     varchar2(100)   null,
CIDADE          varchar2(50)    null,
UF              varchar2(2)     null,
CEP             varchar2(10)    null,
TOTAL_FATURA    NUMBER(8,2)     null,
CODIGO_CLI      NUMBER          NOT NULL,
MATRICULA_VEN   NUMBER          NOT NULL
);

DROP TABLE ESTOQUE CASCADE CONSTRAINTS;

CREATE TABLE ESTOQUE (
DATA_ENTRADA        DATE        NOT NULL,
CODIGO_PRO          NUMBER      NOT NULL,
CODIGO_PRA          NUMBER(3)   NOT NULL,
QUANTIDADE          NUMBER(5)   NOT NULL,
DATA_VALIDADE       DATE        NULL
);

DROP TABLE CAPACIDADE_ESTOQUE CASCADE CONSTRAINTS;

CREATE TABLE CAPACIDADE_ESTOQUE (
CODIGO_PRO  NUMBER      NOT NULL,
CODIGO_PRA  NUMBER(3)   NOT NULL,
QUANTIDADE  NUMBER(5)   NOT NULL
);

DROP TABLE ITEM_PRODUTO CASCADE CONSTRAINTS;

CREATE TABLE ITEM_PRODUTO (
CODIGO_PRO    NUMBER NOT NULL,
NUMERO_PED    NUMBER(6) NOT NULL,  
QUANTIDADE    NUMBER(5) NOT NULL,
PRECO_UNITARIO NUMBER(5,2) NOT NULL,
VALOR_ITEM      NUMBER(7,2) NULL
);

ALTER TABLE PEDIDO ADD CONSTRAINT PK_PEDIDO PRIMARY KEY (NUMERO);

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY(CODIGO_CLI) REFERENCES CLIENTE(CODIGO_CLIENTE)
ADD CONSTRAINT FK_PEDIDO_VENDEDOR FOREIGN KEY(MATRICULA_VEN) REFERENCES VENDEDOR(MATRICULA);

ALTER TABLE ESTOQUE ADD CONSTRAINT FK_ESTOQUE PRIMARY KEY(DATA_ENTRADA,CODIGO_PRO,CODIGO_PRA);

ALTER TABLE ESTOQUE
ADD CONSTRAINT FK_ESTOQUE_PRODUTO FOREIGN KEY(CODIGO_PRO) REFERENCES PRODUTO(CODIGO)
ADD CONSTRAINT FK_ESTOQUE_PRATELEIRA FOREIGN KEY(CODIGO_PRA) REFERENCES PRATELEIRA(CODIGO);

ALTER TABLE CAPACIDADE_ESTOQUE ADD CONSTRAINT PK_CAPACIDADE_ESTOQUE PRIMARY KEY(CODIGO_PRO,CODIGO_PRA);

ALTER TABLE CAPACIDADE_ESTOQUE
ADD CONSTRAINT FK_CAPACIDADE_PRODUTO FOREIGN KEY(CODIGO_PRO) REFERENCES PRODUTO(CODIGO)
ADD CONSTRAINT FK_CAPACIDADE_PRATELEIRA FOREIGN KEY(CODIGO_PRA) REFERENCES PRATELEIRA(CODIGO);

ALTER TABLE ITEM_PRODUTO ADD CONSTRAINT PK_ITEM_PRODUTO PRIMARY KEY(CODIGO_PRO,NUMERO_PED);

ALTER TABLE ITEM_PRODUTO
ADD CONSTRAINT FK_ITEM_PRODUTO FOREIGN KEY(CODIGO_PRO) REFERENCES PRODUTO(CODIGO)
ADD CONSTRAINT FK_ITEM_PEDIDO FOREIGN KEY(NUMERO_PED) REFERENCES PEDIDO(NUMERO);

DROP TABLE PEDIDO CASCADE CONSTRAINTS;

CREATE TABLE PEDIDO (
NUMERO          NUMBER(6)       NOT NULL,
DATA            DATE            NOT NULL,
PRAZO_ENTREGA   DATE            null,
RUA             varchar2(80)    null,
NR              NUMBER(4)       null,
BAIRRO          varchar2(50)    null,
COMPLEMENTO     varchar2(100)   null,
CIDADE          varchar2(50)    null,
UF              varchar2(2)     null,
CEP             varchar2(10)    null,
TOTAL_FATURA    NUMBER(8,2)     null,
CODIGO_CLI      NUMBER          NOT NULL,
MATRICULA_VEN   NUMBER          NOT NULL
);

DROP TABLE ESTOQUE;

CREATE TABLE ESTOQUE (
DATA_ENTRADA        DATE        NOT NULL,
CODIGO_PRO          NUMBER      NOT NULL,
CODIGO_PRA          NUMBER(3)   NOT NULL,
QUANTIDADE          NUMBER(5)   NOT NULL,
DATA_VALIDADE       DATE        NULL
);

DROP TABLE CAPACIDADE_ESTOQUE;

CREATE TABLE CAPACIDADE_ESTOQUE (
CODIGO_PRO  NUMBER      NOT NULL,
CODIGO_PRA  NUMBER(3)   NOT NULL,
QUANTIDADE  NUMBER(5)   NOT NULL
);

DROP TABLE ITEM_PRODUTO;

CREATE TABLE ITEM_PRODUTO (
CODIGO_PRO    NUMBER NOT NULL,
NUMERO_PED    NUMBER(6) NOT NULL,  
QUANTIDADE    NUMBER(5) NOT NULL,
PRECO_UNITARIO NUMBER(5,2) NOT NULL,
VALOR_ITEM      NUMBER(7,2) NULL
);

ALTER TABLE PEDIDO ADD CONSTRAINT PK_PEDIDO PRIMARY KEY (NUMERO);

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY(CODIGO_CLI) REFERENCES CLIENTE(CODIGO_CLIENTE)
ADD CONSTRAINT FK_PEDIDO_VENDEDOR FOREIGN KEY(MATRICULA_VEN) REFERENCES VENDEDOR(MATRICULA);

ALTER TABLE ESTOQUE ADD CONSTRAINT FK_ESTOQUE PRIMARY KEY(DATA_ENTRADA,CODIGO_PRO,CODIGO_PRA);

ALTER TABLE ESTOQUE
ADD CONSTRAINT FK_ESTOQUE_PRODUTO FOREIGN KEY(CODIGO_PRO) REFERENCES PRODUTO(CODIGO)
ADD CONSTRAINT FK_ESTOQUE_PRATELEIRA FOREIGN KEY(CODIGO_PRA) REFERENCES PRATELEIRA(CODIGO);

ALTER TABLE CAPACIDADE_ESTOQUE ADD CONSTRAINT PK_CAPACIDADE_ESTOQUE PRIMARY KEY(CODIGO_PRO,CODIGO_PRA);

ALTER TABLE CAPACIDADE_ESTOQUE
ADD CONSTRAINT FK_CAPACIDADE_PRODUTO FOREIGN KEY(CODIGO_PRO) REFERENCES PRODUTO(CODIGO)
ADD CONSTRAINT FK_CAPACIDADE_PRATELEIRA FOREIGN KEY(CODIGO_PRA) REFERENCES PRATELEIRA(CODIGO);

ALTER TABLE ITEM_PRODUTO ADD CONSTRAINT PK_ITEM_PRODUTO PRIMARY KEY(CODIGO_PRO,NUMERO_PED);

ALTER TABLE ITEM_PRODUTO
ADD CONSTRAINT FK_ITEM_PRODUTO FOREIGN KEY(CODIGO_PRO) REFERENCES PRODUTO(CODIGO)
ADD CONSTRAINT FK_ITEM_PEDIDO FOREIGN KEY(NUMERO_PED) REFERENCES PEDIDO(NUMERO);



ALTER TABLE PEDIDO
ADD CONSTRAINT CK_NUMERO_PEDIDO CHECK (1 <= NUMERO AND NUMERO <= 99999);

--DROP INDEX UK_PF_CNPF;

CREATE UNIQUE INDEX UK_PF_CNPF
ON PF(CNPF);

--DROP INDEX UK_PJ_CNPJ;

CREATE UNIQUE INDEX UK_PJ_CNPJ
ON PJ(CNPJ);

DROP SEQUENCE SEQ_ITEM_ID;


CREATE SEQUENCE SEQ_ITEM_ID
INCREMENT BY 2;


COMMENT ON TABLE ITEM_PRODUTO IS 'Tabela detalha quais produtos e em que quantidade foram incluídos em cada pedido. DEUSDETH É MASSA DMS!!';
COMMENT ON COLUMN ITEM_PRODUTO.CODIGO_PRO IS 'identifica o produto associado ao item do pedido. É usado como chave estrangeira para a tabela de produtos.';
COMMENT ON COLUMN ITEM_PRODUTO.NUMERO_PED IS 'indica o número do pedido ao qual o item pertence. Serve como chave estrangeira para a tabela de pedidos.';
COMMENT ON COLUMN ITEM_PRODUTO.QUANTIDADE IS 'representa a quantidade do produto vendida neste item do pedido. É usada para calcular o valor total do item.';
COMMENT ON COLUMN ITEM_PRODUTO.PRECO_UNITARIO IS 'mostra o preço de venda do produto no momento do pedido. Armazena o valor unitário para manter o histórico, mesmo que o preço mude depois.';
COMMENT ON COLUMN ITEM_PRODUTO.VALOR_ITEM IS 'indica o valor total deste item no pedido. Geralmente é calculado como QUANTIDADE * PRECO_UNITARIO.';

INSERT INTO CLIENTE
SELECT *
FROM DEMO.CLIENTE;

INSERT INTO PF
SELECT *
FROM DEMO.PF;

INSERT INTO PJ
SELECT *
FROM DEMO.PJ;

INSERT INTO PRODUTO
SELECT *
FROM DEMO.PRODUTO;

INSERT INTO VENDEDOR
SELECT *
FROM DEMO.VENDEDOR;

INSERT INTO FONE_CLIENTE
SELECT *
FROM DEMO.FONE_CLIENTE;

INSERT INTO FONE_VENDEDOR
SELECT *
FROM DEMO.FONE_VENDEDOR;

INSERT INTO PRATELEIRA
SELECT *
FROM DEMO.PRATELEIRA;

INSERT INTO PEDIDO
SELECT *
FROM DEMO.PEDIDO;

INSERT INTO ESTOQUE
SELECT *
FROM DEMO.ESTOQUE ;

INSERT INTO CAPACIDADE_ESTOQUE
SELECT *
FROM DEMO.CAPACIDADE_ESTOQUE ;

COMMIT;


